### ISSUE TITLE
there is a scientific paper for this code source?

### ISSUE THREAD

**Issue by charafeddine46** [tzpranto/Team-Formation#1]

**Comment by tzpranto** [comment]
https://dl.acm.org/doi/abs/10.1145/3205455.3205634
This is the one that got me started. You can find more by checking the forward and backward cross-references of this paper.

**Comment by charafeddine46** [comment]
but in your code, you implement the single-objective version, which is the cost of the communication. It's right?

**Comment by tzpranto** [comment]
Yes. I implemented simple GA variants. I adopted the Cross Over and Mutation algorithms from the above-mentioned paper.

**Comment by charafeddine46** [comment]
ok, thank you very much for your rapid answers

**Comment by charafeddine46** [comment]
Please one more questions if you can: 
1- Are you assuming your graph is oriented or undirected? because in the article above they take it as an undirected graph whereas in your code it looks to me like a directed graph. It's right?
2- Which objective function grom the table have you take it?

**Comment by tzpranto** [comment]
Well, I wrote the code a long time ago and don't remember the bits and pieces. It was for an Assignment. I am attaching the report link which should contain the implementation details. Hope this would help you. Feel free to let me know if you have any other queries.
https://github.com/tzpranto/Team-Formation/blob/master/Project%20Report.pdf

**Comment by charafeddine46** [comment]
I will check that. thank you a lot brother
